# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 녹색당 지지선언 2016
email: combacsa@kaist.ac.kr
description: > # this means to ignore newlines until "baseurl:"
  대한민국 2016년 제20대 총선을 맞아 4월 13일 선거일울 하루 앞둔 시점에서
  프로그래머, 그것도 정치하는 프로그래머인 변규홍이 왜 녹색당을 지지하는지
  자세한 사정을 공유합니다.
baseurl: "/votegreen" # the subpath of your site, e.g. /blog
url: "http://combacsa.github.io" # the base hostname & protocol for your site
twitter_username: combacsa
github_username:  combacsa
facebook_username:  combacsa

# Build settings
markdown: kramdown
